### ISSUE TITLE
Padding for headings/titles

### ISSUE THREAD

**Issue by jpia** [once-2021-05-03-bootstrap/portfolio-project-group-a#2]
It's  a personal pet peeve of mine to see some titles touching the borders/edges of a box. So if you can, add some padding.

**Comment by jpia** [comment]
here's an example where the titles in the orange blocks dont have enough padding
![Screen Shot 2021-06-26 at 12 21 40 PM](https://user-images.githubusercontent.com/6011922/123520944-28461300-d679-11eb-8f99-97b915f6829c.png)

**Comment by HairyChronicJr** [comment]
Resolved w/ commit 27a1d9fd
