### ISSUE TITLE
Recipe modal

### ISSUE THREAD

**Issue by HairyChronicJr** [once-2021-05-03-bootstrap/portfolio-project-group-a#7]
Create modal linked to image on recipe page. Modal should display full recipe.

**Comment by jpia** [comment]
Some users may want to print the recipe, make sure to test if the recipe can still be printed from a modal window.

**Comment by HairyChronicJr** [comment]
It prints and is legible. It's not perfect since it still prints the background behind the modal. I've added a print button to each of the modal windows to make it a little easier.

**Comment by jpia** [comment]
Thanks for testing! Print is another media that web developers have to keep in mind. You do not have to implement a custom print.css file on your project, but the following info could help you on future projects:

-  [https://www.smashingmagazine.com/2018/05/print-stylesheets-in-2018/](https://www.smashingmagazine.com/2018/05/print-stylesheets-in-2018/ )
- [https://getbootstrap.com/docs/4.5/getting-started/browsers-devices/#printing](https://getbootstrap.com/docs/4.5/getting-started/browsers-devices/#printing)

**Comment by HairyChronicJr** [comment]
Thanks for those links! I'm going to close out this issue and create a new one for the print sheet.
